
package com.bnq.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://www.tmp.web/ws/hello")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://www.tmp.web/ws/hello/HelloWorld/getProductRequest", output = "http://www.tmp.web/ws/hello/HelloWorld/getProductResponse")
    public long getProduct(
        @WebParam(name = "arg0", partName = "arg0")
            long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://www.tmp.web/ws/hello/HelloWorld/sayHelloWorldFromRequest", output = "http://www.tmp.web/ws/hello/HelloWorld/sayHelloWorldFromResponse")
    public String sayHelloWorldFrom(
        @WebParam(name = "arg0", partName = "arg0")
            String arg0);

}
